# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EpitechEisenhower' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EpitechEisenhower
	pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'GoogleSignIn'
    #   pod 'FacebookCore'
    #   pod 'FacebookLogin'
    #pod 'FacebookShare'
    pod 'FBSDKLoginKit'
    pod 'Firebase/Database'
end
